export const EQUIPMENT_EQUIPMENT: Record<string, string> = {
  KACANG_TANAH: 'Kacang Tanah',
  TEBU: 'Tebu',
  JAGUNG: 'Jagung',
  SAWI: 'Sayur',
  TEMBAKAU: 'Tembakau',
  KOPI: 'Kopi',
  KENTANG: 'Kentang',
  KARET: 'Karet',
  PADI_LADANG: 'Padi Ladang',
  WORTEL: 'Wortel',
  TOMAT: 'Tomat',
  PADI_SAWAH: 'Padi Sawah',
  KEDELAI: 'Kedelai',
  CENGKEH: 'Cengkeh',
  UBI_KAYU: 'Ubi Kayu',
  BAWANG_MERAH: 'Bawang Merah',
  KOL: 'Kol',
  UBI_JALAR: 'Ubi Jalar',
  LAINNYA: 'Lainnya'
}